<style>
    .tag_block{
        float: left;
        margin: 5px 10px;
        padding: 3px 6px;
        border: solid 1px #444;
        color: #444;
    }
    .tag_block:hover{
        text-decoration: none;
        background: #eee;
        border: solid 1px #777;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
                <?php foreach ($this->getTags() as $item): ?>
                        <a href="" class="tag_block"><?php echo $item->getTitle() ?></a>
                <?php endforeach; ?>

        </div>
        <div class="col-xs-12">
            <div class="table-responsive">
                <table summary="This table shows how to create responsive tables using Bootstrap's default functionality" class="table table-bordered table-hover">
                    <caption class="text-center">An example of a responsive table based on <a href="https://getbootstrap.com/css/#tables-responsive" target="_blank">Bootstrap</a>:</caption>
                    <tbody>
                        <?php foreach ($this->getPosts() as $item): ?>
                            <tr>
                                <td><a href="/news/index/post?id=<?php echo $item->getId(); ?>"><?php echo $item->getTitle(); ?></a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>



            </div>
        </div>
    </div>
</div>
