<style>
    .tag_block{
        float: left;
        margin: 5px 10px;
        padding: 3px 6px;
        border: solid 1px #444;
    }
    .tag_block:hover{
        text-decoration: none;
        background: #eee;
        border: solid 1px #777;
    }
    .tags_cloud{
        padding-bottom: 50px;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12 tags_cloud">
                <?php foreach ($this->getTags() as $item): ?>
                        <a <?= isset($_GET['with-tag']) ? $_GET['with-tag'] == $item->getId() ? 'style="background: #555; color: #fff"' : 'style="color: #444"' : '' ?> href="" class="tag_block"> <?php echo $item->getTitle() ?> </a>
                <?php endforeach; ?>

        </div>
        <div class="col-xs-12">
            <div class="table-responsive">
                <table summary="This table shows how to create responsive tables using Bootstrap's default functionality" class="table table-bordered table-hover">
                    <caption class="text-center">An example of a responsive table based on <a href="https://getbootstrap.com/css/#tables-responsive" target="_blank">Bootstrap</a>:</caption>
                    <tbody>
                        <?php foreach ($this->getPosts() as $item): ?>
                            <tr>
                                <td><a href="<?= $item->getPostLink(); ?>"><?php echo $item->getTitle(); ?></a></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
